### PR TITLE
Update signup.php

### PR DESCRIPTION
**Pull request by modev32**
In Mysqli there is no need to use 'real_escape_string' as it dose it by it self if you execute it the right way
I have updated the old method to the correct one and removed string escaping

### CODE REVIEW

**Comment by arjunsk** [comment]
Thank you

**Comment by modev32** [comment]
You are welcome, there's a type in line 57 replace & with $ my mistake sorry :)

**Comment by arjunsk** [comment]
Hey, i was wondering what is the first param
$stment->bind_param("ssssssi", $name, $username, $password, $phone, &address, $pincode, 1);

**Comment by modev32** [comment]
"S" refers to String while "i" refers to integer
So $name, $username... etc are strings as i have read the structure of your database. While "1" that refers to account vertification is an integer so we tell the database executer "this is an integer value so dont accept anything else"
Same goes with strings as the executer will blind them as strings so it's much more safer whatever the user types.
They are sorted as the vaules are sorted started with 5 strings and ended with one integer.

**Comment by arjunsk** [comment]
Ok.. Thanks for the info. Can you make the pull request again. I just reverted the earlier changes.

**Comment by modev32** [comment]
Im new to this i tried to submit again but it says i have to be branch or something like that.
Anyway i guess you can see it from the history you can submit it and please give it a try as i just wrote it without trying.
Plus you can read more about Mysqli prepared statments using PDO method .. Which is the same method i used. Its faster & easier and safer. I will try to edit the other files once i get time as i edited this using my phone :)

**Comment by arjunsk** [comment]
Thanks alot for contributing to this project.

I am also relatively new to github. 
Please make the necessary changes once you have tested the code.
(My net connection is pathetic, so i am not able to test it properly. )
Currently, i am keeping the earlier code, as it was tested and worked fine for me.

I am planing to write an article soon, on Foodkart V0.3 . It has alot of improvements. 

http://www.arjunsk.com/html5/how-to-setup-loginregister-using-ionic-cordova-part-5/#comment-2767950521

**Pull request merged**
